### ISSUE TITLE
[Feature Suggestion] Plymouth Support

### ISSUE THREAD

**Issue by VGrol** [agherzan/yubikey-full-disk-encryption#19]
Plymouth is a tool used to display the initial bootstages better. 
You can [read more about it here.](https://wiki.archlinux.org/index.php/Plymouth)

It however, requires the Encrypt hook to be replaced with Plymouth-encrypt.
Since YKFDE replaces the encrypt module as well, I was wondering if you could make a plymouth compatible version.

**Comment by Vincent43** [comment]
That should be possible. Debian version supports plymouth already: https://github.com/cornelinux/yubikey-luks/blob/master/key-script#L14 . I'm not using plymouth on Arch right now. If you want, you may try to tweak it yourself and give us feedback.

**Comment by agherzan** [comment]
It's an interesting feature request. I'm not a plymouth user either but it shouldn't be a hard task.

**Comment by Vincent43** [comment]
I think it can be implemented within same hook, just check if plymouth is running and then read password from plymouth instead of console.

**Comment by doniom** [comment]
Hello, is it possbile to support plymouth-encrypt? Please

**Comment by benruijl** [comment]
Here is a patch of the ykfde hook with support for Plymouth: 
[ykfde.txt](https://github.com/agherzan/yubikey-full-disk-encryption/files/3122127/ykfde.txt)

For some reason I cannot get on-screen text to work. The `plymouth-encrypt` hook does have text below the password prompt and I have no idea why it doesn't work in the ykfde hook. Any suggestions?

**Comment by Vincent43** [comment]
@benruijl thx, if you open PR with your patch included it will be easier to investigate 😄 .
