### ISSUE TITLE
Use a proper KDF + salt instead of sha256sum

### ISSUE THREAD

**Issue by AbdussamadA** [agherzan/yubikey-full-disk-encryption#26]
Please use a proper kdf and salting instead of sha256sum. Sha256 can be done very quickly so you can create rainbow tables for common passwords. You can use scrypt for instance and a 64 bit random salt.

**Comment by Vincent43** [comment]
This isn't what this project aims for. We create Luks passphrases which are already protected by KDF using pbkdf2 or argon2 depending on Luks version.

Sha256 is used to additionally increase passphrase entropy. Keep in mind that Sha256 is only 2/3 of the final passphrase so you can't try to guess it directly basing on luks header. Even if attacker knows it, they still need the yubikey - benefits of 2FA :smile:

Anyway thanks for your comment.

**Comment by agherzan** [comment]
I think @Vincent43 summarized it well. Nothing to add here.
