### ISSUE TITLE
How does this work with an encrypted boot partition?

### ISSUE THREAD

**Issue by filipe-cantarelli** [agherzan/yubikey-full-disk-encryption#33]
Hello,

I have an UEFI boot setup where my EFI system partition is unencrypted, but my boot partition is encrypted. In fact, I don't have a proper boot partition, boot lives in the root partition, which is encrypted.

Following the README I'm able to have this working after I manually unlock boot with a passphrase.
Current boot process steps:
(passphrase for unlocking boot) -> GRUB -> (yubikey for unlocking root) -> system booted.

I'm wondering if yubikey can be used for unlocking the boot partition as well. Eliminating step 1.

**Comment by Vincent43** [comment]
That would need patching GRUB which is non-trivial and rather unlikely. You may consider booting from [EFISTUB](https://wiki.archlinux.org/index.php/EFISTUB), i.e. combine microcode+kernel+initramfs+cmdline, put it to EFI system partition and protect with [UEFI Secure Boot](https://wiki.archlinux.org/index.php/Secure_Boot). There are [existing projects which will handle this for you](https://github.com/andreyv/sbupdate). It can be used with [systemd-boot](https://wiki.archlinux.org/index.php/Systemd-boot).

**Comment by filipe-cantarelli** [comment]
Thanks,

I'll take a look into those options.

**Comment by pbartyik** [comment]
@filipe-cantarelli I'm in the same situation. What solution did you end up using?
