### ISSUE TITLE
AUR PACKAGE missing

### ISSUE THREAD

**Issue by TheRojam** [agherzan/yubikey-full-disk-encryption#39]
It seems that the latest aur package was missing. 
I could be your co-maintainer.

**Comment by Vincent43** [comment]
AFAIK there was never package for this project on AUR. If you're familiar with AUR you may create one yourself. [PKGBUILD](https://github.com/agherzan/yubikey-full-disk-encryption/blob/master/PKGBUILD) is ready.

**Comment by TheRojam** [comment]
the there was a another package, that was reason i could install it :D

**Comment by agherzan** [comment]
@theRojam share with us the Web link.

**Comment by Vincent43** [comment]
There is https://aur.archlinux.org/packages/mkinitcpio-ykfde/ which also leverages YubiKey for LUKS but it's not compatible nor related to our project here.

**Comment by agherzan** [comment]
I see. So it's another project there. @TheRojam if you want to submit one and maintain it I'm OK with that.

**Comment by TheRojam** [comment]
atm i just opend a [gitrepo](https://github.com/TheRojam/AUR-yubikey-full-disk-encryption) as base. i will submit later to aur.

**Comment by TheRojam** [comment]
aur package is now available https://aur.archlinux.org/packages/yubikey-full-disk-encryption-git/

**Comment by agherzan** [comment]
@theRojam wouod you add it to the readme too? Thanks. Looks good.

**Comment by Vincent43** [comment]
@TheRojam I made a mistake in recent PKGBUILD edit which makes it broken, it have to be fixed like this: https://github.com/agherzan/yubikey-full-disk-encryption/commit/2b977b90347b8cc64996e106da44491f276e1b26

**Comment by TheRojam** [comment]
> @TheRojam wouod you add it to the readme too?
I will fork this repo to my rprofile and do it.

**Comment by TheRojam** [comment]
> @TheRojam I made a mistake in recent PKGBUILD edit which makes it broken, it have to be fixed like this: [2b977b9](https://github.com/agherzan/yubikey-full-disk-encryption/commit/2b977b90347b8cc64996e106da44491f276e1b26)
I will take a look soon.
