### ISSUE TITLE
ykfde suspend: invalid mount option for btrfs

### ISSUE THREAD

**Issue by relatev** [agherzan/yubikey-full-disk-encryption#45]
This is a really great tool!
I just have one minor issue with using a btrfs filesystem with the ykfde suspend service. It fails because of the barrier=0 option fix for ext4 filesystems, because it doesn't seem to be an option for btrfs. Got it working with commenting out the whole fix. I would suggest adding a check whether the filesystem really is ext4 inside the if before remount it.

**Comment by Vincent43** [comment]
Thank you for the report. btrfs mount syntax isn't 100% compatible with ext4 but https://github.com/agherzan/yubikey-full-disk-encryption/commit/ddd4eb2feb685c92b0f21502e29c74a1e0fd08b0 should fix the issue.

**Comment by TheRojam** [comment]
Ping me if theres a new release of the aur package needed.

**Comment by relatev** [comment]
This fixed it, thanks!
