### ISSUE TITLE
Are those scripts and strong passphrase generation compatible with yubikey-luks ?

### ISSUE THREAD

**Issue by stman** [agherzan/yubikey-full-disk-encryption#48]
Hello.

This is a very simple question :

Do the way you compute the passphrase with the yubikey is the same as the "yubikey-luks" modules that we usually use to cypher the filesystem of an install under ubuntu ?

Meaning, can it be used to unlock standalone partition on removable medias for example, of backups of such luks partition of backup hard drive with the yubikey itself ?

**Comment by Vincent43** [comment]
Yes but only if you enable both `CONCATENATE=1` and `HASH=1` in [yubikey-luks config](https://github.com/cornelinux/yubikey-luks/blob/master/ykluks.cfg#L4).

**Comment by stman** [comment]
Thank you for this precise answer. And when using the following default command line to enroll a yubikey on a LUKS partition, after installing the "yubikey-lusk" package with 

`sudo apt-get install yubikey-luks`

 without editing anything (Using its default configuration), and enrolling the yubikey with : 

`sudo yubikey-luks-enroll -d /dev/sda3 -s 7` command, is it the case ? Do those options Contatenate and Hash are set properly ?

**Comment by Vincent43** [comment]
No, both options I mentioned default to 0 so your passphrase isn't compatible with this project.

> For unknown reasons, when installing the "yubikey luks" package as I did, the command yubikey-luks-open is not included. It sucks.

What distro are you using? `yubikey-luks-open`  is available only in ubuntu 19.04 or debian 10. If you use older distro you may install it [from there](https://packages.ubuntu.com/disco/all/yubikey-luks/download).

**Comment by Vincent43** [comment]
Hm, it seems that ubuntu/debian packages mistakenly install `yubikey-luks-open` to /usr/lib instead of /usr/bin which means you have to invoke it with full path like `/usr/lib/yubikey-luks-open` rather than `yubikey-luks-open`.

**Comment by stman** [comment]
Thank a lot for all your precise explanations.
I've read the `yubikey-luks` package config file, and the default config sets those two variables to zero.

Meaning that the effective passphrase generated is just the output of the challenge function of the raw password. I could finaly mount the volume entering this string and it worked.

yubikey-luks folks could have included a small documentation explaining all this rapidely, that there are four different modes to generate the long passphrase from the challenge from the password.

And yes, the mode you propose by default for your driver is therefore the most secure because it generates the longest string.

Kind regards, 

Frederic.
