### ISSUE TITLE
Suspend on ram fails when using luks on lvm

### ISSUE THREAD

**Issue by PhotonQuantum** [agherzan/yubikey-full-disk-encryption#51]
We've already known that ext4 barrier prevents system from suspending, so remounting cryptdevice with nobarrier option will solve the problem.

But [src/ykfde-suspend#L79](https://github.com/agherzan/yubikey-full-disk-encryption/blob/master/src/ykfde-suspend#L79) can't handle ext4 filesystems on lvm layers as is described at [ArchWiki](https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#LVM_on_LUKS) now, hanging the suspend process.

I believe that the problem can be solved by detecting ext4 filesystems running on crypted lvms and remount them accordingly, or adding a config option to allow users specify their own ext4 logic partitions.

However, I haven't figured out yet whether these approaches are feasible and how they can be implemented. Any ideas?

**Comment by agherzan** [comment]
I think we should probably expose a knob for this. cc @Vincent43

**Comment by Vincent43** [comment]
I found something that can help fixing this: https://github.com/jrouleau/arch-luks-suspend/commit/89b075a9c7c6eaa91aedd1a03f71f280264b2b28

**Comment by Vincent43** [comment]
Fixed by https://github.com/agherzan/yubikey-full-disk-encryption/commit/4fa9737d2066b3da672f4ce3715f6a7c37f7f987
