### ISSUE TITLE
Add descriptions

### ISSUE THREAD

**Issue by fishsalted** [agherzan/yubikey-full-disk-encryption#52]
The script used dejavu-sans font (plymouth support ) . 
If you not install dejavu-sans , plymouth message will not displaying properly.
So i think, it should write in readme.

**Comment by Vincent43** [comment]
The used font is decided by [plymouth](https://aur.archlinux.org/packages/plymouth/) and [ttf-dejavu](https://www.archlinux.org/packages/extra/any/ttf-dejavu/) is optional dependency there. This isn't what we can control form here.

**Comment by fishsalted** [comment]
But [/src/install/ykfde](https://github.com/agherzan/yubikey-full-disk-encryption/blob/master/src/install/ykfde) file (line.62) added DejaVuSans.ttf file.
I don't know if it's related to this. I am very sorry if I misunderstood.

**Comment by Vincent43** [comment]
We copy the font if it's available but it's not our requirement - it's plymouth requirement.
