### ISSUE TITLE
External LUKS header

### ISSUE THREAD

**Issue by funboytwo** [agherzan/yubikey-full-disk-encryption#66]
I currently have my luks header on a usb drive and I’m trying to add ykfde to a free keyslot. However, `ykfde-enroll` and `ykfde-open` don’t seem to read out the additional parameters with the syntax `-- --header /$headerlocation`, so the luks device isn’t recognized. What am I missing?

On another note, the header flag does seem to be recognized by`ykfde-format` since it shows up in luksDump. There’s no way to verify it though since I can’t open it.

**Comment by funboytwo** [comment]
Scratch that, cloning the git directly as opposed to using the Arch repo package solves this problem and recognizes the extra cryptsetup params with `-- --$param`

**Comment by Vincent43** [comment]
Yes it was recently added to `ykfde-open` with https://github.com/agherzan/yubikey-full-disk-encryption/commit/3ed7c196a9ace1b184bc6777b4269172df18dedb . Note that `ykfde-enroll` still doesn't support that.
