### ISSUE TITLE
YKFDE_CHALLENGE= in /etc/ykfde.conf appears to not work

### ISSUE THREAD

**Issue by GIJack** [agherzan/yubikey-full-disk-encryption#69]
Hi, the YKFDE_CHALLENGE= key appears to not work /etc/ykfde.conf

I am putting the exact same password to unlock it with 2FA, but with 1FA it doesn't seem to go.

edit: As in it seems to fail to authenticate. "No Key available with this passphrase"

Running latest archlinux

$ pacman -Q yubikey-full-disk-encryption
yubikey-full-disk-encryption r143.2ce7aa7-1

$ pacman -Q cryptsetup
cryptsetup 2.3.4-1

**Comment by Vincent43** [comment]
same challenge will result in different luks passphases in 2FA and 1FA so you have to enroll then both first. Keep note that using same challenge for 2FA make it no better than 1FA.

**Comment by GIJack** [comment]
How do you enroll 1FA, there are no instructions, just 2FA.

Here is what I am trying to do: Turn on, hit the button, and system boots.

**Comment by Vincent43** [comment]
For 1FA you need to uncomment  and set [YKFDE_CHALLENGE](https://github.com/agherzan/yubikey-full-disk-encryption/blob/master/src/ykfde.conf#L8) to non empty value then enroll it as instructed in [README](https://github.com/agherzan/yubikey-full-disk-encryption#enroll-ykfde-passphrase-to-existing-luks-encrypted-volume).

**Comment by Falroi** [comment]
Any value or is this something that needs to be generated?

**Comment by Vincent43** [comment]
@Falroi any value no longer than 64 characters which is yubikey limitation. It's up to you.

**Comment by NgoHuy** [comment]
very strange, I enter challenge to config, and verify it worked manually. But didnot work when booting,

**Comment by Vincent43** [comment]
@NgoHuy what happens on boot then? Did you regenerated initramfs after editing ykfde.conf? You may also enable [debug mode](https://github.com/agherzan/yubikey-full-disk-encryption/blob/master/src/ykfde.conf#L53) to see more info

**Comment by Vincent43** [comment]
Do you mean you have multiple encrypted partitions protected with different ykfde challenges and want to decrypt them all on boot? Such scenario isn't really supported by this project.

**Comment by NgoHuy** [comment]
> Do you mean you have multiple encrypted partitions protected with different ykfde challenges and want to decrypt them all on boot? Such scenario isn't really supported by this project.

yes, I know, I must create different config and different hooks, it worked. But ykfde-enroll only support /etc/ykfde.conf, I must create the response as key to add manually by using cryptsetup. another way is edit main file, but edited again when done. Should we have option to point another config file?
