### ISSUE TITLE
Make udisks dependency optional?

### ISSUE THREAD

**Issue by thithib** [agherzan/yubikey-full-disk-encryption#70]
Hi and thanks a lot for this great and quite useful project!

I've been wondering if you would consider making the use of `udisksctl` optional. At least on Arch Linux, [udisks2](https://www.archlinux.org/packages/extra/x86_64/udisks2/) brings and pulls many things I don't need, just to allow **unprivileged use** of `ykfde-open` while your tool is otherwise attractively simple and standalone.

I think it would be rather straightforward to move `udisks2` (and thus `expect` too) to `optdepends`, and check if `udisksctl` and `expect` are available on the system at runtime when reaching the unprivileged use case. What do you think?

**Comment by Vincent43** [comment]
Without udisks `ykfde-open` can't be used unprivileged, do you want it to check for udisks/expect while running unprivileged and bail-out if they aren't  available?

**Comment by thithib** [comment]
Precisely, yes.

**Comment by Vincent43** [comment]
@thithib please test if https://github.com/agherzan/yubikey-full-disk-encryption/pull/71 works for you.

**Comment by thithib** [comment]
It works for me, thanks!

You may want to redirect `stderr` too, although I don't know in what cases "diagnostic messages" mentioned in the manual would be output with `command -v`...

**Comment by Vincent43** [comment]
I added `stderr` redirect, thx.
