### ISSUE TITLE
1FA and multiple Yubikey

### ISSUE THREAD

**Issue by rajil** [agherzan/yubikey-full-disk-encryption#80]
Hello,

I am using the primary key was 1FA which is working well. However, I want to register my secondary key incase the primary one gets lost.

At the moment i have populated YKFDE_CHALLENGE="" with the string which the key emits on short touch. This passphrase is set by Yubico as a factory setting. My backup key has a different default passphrase. Can YKFDE_CHALLENGE accept multiple passphrase corresponding to each of my yubikey?

Thanks

**Comment by Vincent43** [comment]
There can be only one value for `YKFDE_CHALLENGE` in 1fa setup. You can use the same value for multiple keys which will still result with different luks passwords per key which need to be enrolled separately.

**Comment by agherzan** [comment]
@rajil Hope that the above clarifies it. I'll close the issue for now.
