### ISSUE TITLE
[Question]some question

### ISSUE THREAD

**Issue by 1m-N00b** [agherzan/yubikey-full-disk-encryption#84]
Q1:Does this require the yubikey to be connected to usb(typec) before powering it on? Or do you have to stick it in when prompted by the luks pw?
Q2:Can I add a regular pw in addition to yubikey?
Q3:Is it safe to remove the luks after deactivation?
Q4:Can I use it at the same time as PAM such as sudo?

**Comment by Erick555** [comment]
Q1: Boot script will wait 30s for you to insert key (time is configurable). After that it will ask for non-ykfde password but you can skip it and try again with key with another 30s and so on. The runtime scripts need yubikey inserted at time of invocation.

Q2: yes, you can add another password to different luks keyslot number. This is even recommended backup solution in case you lose the key. Keep in mind that backup password should be comparably strong to ykfde one.

Q3: I don't fully understand the question, could you elaborate?

Q4: It doesn't interfere with using yubikey with sudo

**Comment by 1m-N00b** [comment]
sry eng is my 2nd language so i use translator
Q3 mean **Is it safe to unplug yubikey after unlocking luks?**

**Comment by Erick555** [comment]
yes
