### ISSUE TITLE
Shutdown hook is not copying initramfs files so ykfde only does normal suspend

### ISSUE THREAD

**Issue by noeamiot** [agherzan/yubikey-full-disk-encryption#91]
During boot the shutdown hook throws this error : `cp:can not create directory :'/run/initramfs/' no such file or directory`

The initramfs files necessary for the luks-locking suspend are not created in /run/initramfs so we do a normal suspend [see suspend script](https://github.com/agherzan/yubikey-full-disk-encryption/blob/dcaac005b10eac132ac663c268318bd909bf027c/src/ykfde-suspend#L51).

There is already an [issue](https://github.com/archlinux/mkinitcpio/issues/104) about this on the mkinitcpio repository and a [bug reported](https://bugs.archlinux.org/task/74534).

While waiting for a fix on mkinicpio or whatever is causing this problem, you can check [here](https://github.com/archlinux/mkinitcpio/issues/104#issuecomment-1130534848) for a temporary solution.

**Comment by agherzan** [comment]
I would wait for a fix in mkinicpio to avoid overcomplicating things here. That should come soon.

**Comment by Vincent43** [comment]
This should be fixed in mkinitcpio v34, https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/commit/7930b797a255505f84120f07cab3893cc1f31a3e
